### ISSUE TITLE
directly modify fingerprint

### ISSUE THREAD

**Issue by li161** [hellodword/anti-fingerprinting#1]
Do you have the code directly modify chromium originally code

**Comment by hellodword** [comment]
What does the `fingerprint` mean here?

1. tls/http2/quic/... fingerprinting: I don't think it's a good idea to do this with the entire chromium project, I prefer to implement it as a library in different languages, or as [cronet bindings](https://github.com/search?q=cronet&type=repositories)
2. js browser fingerprinting: I do have a chromium fork working on that, but it's in very early stage and closed-source now, maybe open source in the future :)
